version: '3'
services:
  cropion_rover:
    build: .
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # For GPS
      - "/dev/ttyACM0:/dev/ttyACM0"  # For other serial devices
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI applications
    network_mode: "host"
    privileged: true  # Required for hardware access 